FROM ubuntu
LABEL author=prathameshmore

# Update package list and install Apache
RUN apt-get update && \
    apt-get install -y apache2

# Copy the index.html file to the web server root directory
COPY index.html /var/www/html/index.html

# Set the working directory to the web server root directory
WORKDIR /var/www/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start Apache in the foreground as the entry point
CMD ["apache2ctl", "-D", "FOREGROUND"]
