FROM ubuntu:20.04  # Use a specific Ubuntu version for consistency

LABEL author=prathameshmore

RUN apt-get update && apt-get install -y apache2

COPY index.html /var/www/html/index.html

WORKDIR /var/www/html

EXPOSE 80

ENTRYPOINT ["apache2ctl", "-D", "FOREGROUND"]  # Use apache2ctl for Ubuntu
